# Dependencies
pygments:         false


# Permalinks
permalink:        pretty


# Settings
destination:      ./
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             OOCN
url:              http://oocn.eu
description:      Sitio onde se respira pol√≠tica com significativa qualidade de ar interior 

# Links
expo_repo:        https://oocn.eu
expo_new_issue:   https://oocn.eu

docs:             http://oocn.eu
blog:             http://oocn.eu
